import Head from 'next/head'
import Image from 'next/image'
import PizzaList from '../components/PizzaList'
import Slider from '../components/Slider'
import UpperBanner from '../components/UpperBanner'

export default function Home() {
  return (
    <div>
      <Head>
        <title>GrabIt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <UpperBanner/>

      <div className='bg-black h-3 md:h-8'></div>
      
      <Slider/>

      <PizzaList/>
    </div>
  )
}
